swagger: '2.0'
info:
  description: iRODS Metadata Templates
  version: 1.0.0
  title: iRODS Metadata Templates
  # put the contact info for your development or API team
  contact:
    email: michael.c.conway@gmail.com

  license:
    name: BSD 3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: curators
  description: Operations available to regular users and curators

paths:
  /templates:
    get:
      tags:
      - developers
      summary: searches templates
      operationId: searchTemplates
      description: |
        By passing in the appropriate options, you can search for
        available templates
      produces:
      - application/json
      parameters:
      - in: query
        name: searchString
        description: pass an optional search string for looking up inventory
        required: false
        type: string
      - in: query
        name: skip
        description: number of records to skip for pagination
        type: integer
        format: int32
        minimum: 0
      - in: query
        name: limit
        description: maximum number of records to return
        type: integer
        format: int32
        minimum: 0
        maximum: 50
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/MetadataTemplate'
        400:
          description: bad input parameter

definitions:
  MetadataTemplate:
    type: object
    required:
    - id
    - name

    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: Dublin Core

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /michael-conway/IRODSMETADATATEMPLATES/1.0.0
schemes:
 - https
