swagger: "2.0"
info:
  description: "iRODS Metadata Templates"
  version: "1.0.0"
  title: "iRODS Metadata Templates"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/metadata/template/1.0.0"
tags:
  - name: "Templates"
    description: "Secured Admin-only calls"
  - name: "Metadata"
    description: "Operations available to regular users and curators"
paths:
  /template/findByGuid:
    get:
      tags:
        - "Templates"
      summary: "Get template by id"
      operationId: "findTemplateByGuid"
      description: |
        By passing in the appropriate options, you can search for
        available templates
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "guid"
          description: "pass an a guid to get template"
          required: false
          type: "string"
      responses:
        '200':
          description: "search results matching criteria"
          schema:
            items:
              $ref: '#/definitions/Template'
        '400':
          description: "bad input parameter"
definitions:
  Template:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      templateName:
        type: "string"
      createTs:
        type: "string"
        format: "date-time"
      modifyTs:
        type: "string"
        format: "date-time"
      version:
        type: "integer"
        format: "int32"
      description:
        type: "string"
      guid:
        type: "string"
        format: "UUID"
      access_type:
        type: "string"
      owner:
        type: "string"
      elements:
        $ref: '#/definitions/Metadata'
    xml:
      name: "Template"
  Metadata:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      attribute:
        type: "string"
      defaultValue:
        type: "string"
      attributeUnit:
        type: "string"
      type:
        type: "string"
      required:
        type: "boolean"
      options:
        type: "string"
      access_type:
        type: "string"
      validationExp:
        type: "string"
      guid:
        type: "string"
        format: "UUID"
      elements:
        $ref: '#/definitions/Metadata'
    xml:
      name: "Metadata"
